Args = --initialize-at-build-time=org.slf4j.simple \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-run-time=software.amazon.awssdk.crt \
       --initialize-at-run-time=com.googlecode.lanterna \
       -H:+ReportExceptionStackTraces \
       --no-fallback
